baseURL = "https://blog.coderdan.uk"
languageCode = "en-us"
title = "Coder Dan | Blog"
theme = "KeepIt"

enableEmoji = true
enableRobotsTXT = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
  
[Permalinks]
  posts = "/:year/:filename/"
  
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    since = 2021
    author = "CoderDanUK"             # Author's name
    subtitle = "Software Engineer"    # Subtitle
    cdn_url = ""                      # Base CDN URL
    home_mode = ""                    # post or other
    dateFormatToUse = ""              # set date format, default "2 January 2006"

    avatar = "/images/me/avatar.jpg" #comment it to use gravatar
    socialShare = true

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    GitHub = "CoderDanUK"

[params.share]
Twitter = true
Facebook = true
Linkedin = true

[author]
  name = "CoderDanUK"
  
  [params.publisher]
    name = "CoderDanUK"
